var myString;
var myNum;
var myBool;
var myVar;
// let strArr: string[];
// let boolArr: boolean[];
var strArr;
var boolArr;
myString = 'Hello';
myNum = 22;
myBool = true;
myVar = 'hello';
strArr = ['hi', 'how', 'are', 'you'];
boolArr = [true, false, true];
console.log(strArr);
